### ISSUE TITLE
(trayicon) fails to build

### ISSUE THREAD

**Issue by jbeich** [letoram/arcan#206]
Regressed by edd8a518881b

```c
$ pkg install arcan meson pkgconf
$ cd src/tools/trayicon
$ meson setup _build
$ meson compile -C _build
[...]
../src/parse-lemon.c:13:6: error: no member named 'italic' in 'struct tui_screen_attr'
                a->italic = val;
                ~  ^
../src/parse-lemon.c:16:6: error: no member named 'underline' in 'struct tui_screen_attr'
                a->underline = val;
                ~  ^
../src/parse-lemon.c:19:6: error: no member named 'bold' in 'struct tui_screen_attr'
                a->bold = val;
                ~  ^
../src/parse-lemon.c:30:6: error: no member named 'italic' in 'struct tui_screen_attr'
                a->italic = !a->italic;
                ~  ^
../src/parse-lemon.c:30:19: error: no member named 'italic' in 'struct tui_screen_attr'
                a->italic = !a->italic;
                             ~  ^
../src/parse-lemon.c:33:6: error: no member named 'underline' in 'struct tui_screen_attr'
                a->underline = !a->underline;
                ~  ^
../src/parse-lemon.c:33:22: error: no member named 'underline' in 'struct tui_screen_attr'
                a->underline = !a->underline;
                                ~  ^
../src/parse-lemon.c:36:6: error: no member named 'bold' in 'struct tui_screen_attr'
                a->bold = !a->bold;
                ~  ^
../src/parse-lemon.c:36:17: error: no member named 'bold' in 'struct tui_screen_attr'
                a->bold = !a->bold;
                           ~  ^
../src/parse-lemon.c:109:15: error: no member named 'underline' in 'struct tui_screen_attr'
                state->attr.underline = true;
                ~~~~~~~~~~~ ^
10 errors generated.
```
