### ISSUE TITLE
(core) fails to build with Clang atomics

### ISSUE THREAD

**Issue by jbeich** [letoram/arcan#184]
Regressed by 8cf5a6c1e832

```
$ cc --version
FreeBSD clang version 9.0.1 (git@github.com:llvm/llvm-project.git c1a0a213378a458fbea1a5c77b315c7dce08fd05) (based on LLVM 9.0.1)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
```

```c
$ cmake /path/to/arcan/src
$ gmake
[...]
src/engine/arcan_conductor.c:41:2: error: address argument to atomic operation must be a pointer to
      _Atomic type ('uint64_t *' (aka 'unsigned long *') invalid)
        atomic_store(arcan_watchdog_ping, arcan_timemillis());
        ^            ~~~~~~~~~~~~~~~~~~~
/usr/include/stdatomic.h:363:2: note: expanded from macro 'atomic_store'
        atomic_store_explicit(object, desired, memory_order_seq_cst)
        ^                     ~~~~~~
/usr/include/stdatomic.h:256:2: note: expanded from macro 'atomic_store_explicit'
        __c11_atomic_store(object, desired, order)
        ^                  ~~~~~~
src/engine/arcan_conductor.c:560:3: error: address argument to atomic operation must be a pointer to
      _Atomic type ('uint64_t *' (aka 'unsigned long *') invalid)
                atomic_store(arcan_watchdog_ping, arcan_timemillis());
                ^            ~~~~~~~~~~~~~~~~~~~
/usr/include/stdatomic.h:363:2: note: expanded from macro 'atomic_store'
        atomic_store_explicit(object, desired, memory_order_seq_cst)
        ^                     ~~~~~~
/usr/include/stdatomic.h:256:2: note: expanded from macro 'atomic_store_explicit'
        __c11_atomic_store(object, desired, order)
        ^                  ~~~~~~
2 errors generated.
```
