### ISSUE TITLE
(tui) Fails to build on DragonFly, FreeBSD < 13, NetBSD, OpenBSD

### ISSUE THREAD

**Issue by jbeich** [letoram/arcan#258]
Regressed by 8095dce5433d. Found during FreeBSD packaging (12.* is [supported](https://www.freebsd.org/security/#sup) until 2024-06-30) and DragonFly CI (masked by unrelated noise).

```c
src/shmif/tui/lua/tui_lua.c:2993:24: error: use of undeclared identifier 'AT_EMPTY_PATH'
                ib->cwd_fd, src, &s, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW)){
                                     ^
1 error generated.
```

See also https://github.com/freebsd/freebsd-src/commit/73a642c47955

**Comment by jbeich** [comment]
To be accurate, `AT_EMPTY_PATH` (and `O_PATH`) is also missing in FreeBSD 13.0 but 13.0 has been unsupported since 2022-08-31.

**Comment by letoram** [comment]
the joys of fd relative addressing continues, this is so peripheral that a 0 macro will do, thanks.
